server:
  port: 8085
spring:
  application:
    name: investigator-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/investigators}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8881/realms/murdercase}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8881/realms/murdercase/protocol/openid-connect/certs}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: investigator-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8881}
  realm: ${KEYCLOAK_REALM:murdercase}
  client-id: ${KEYCLOAK_CLIENT_ID:murdercase-backend}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:UOZ81WSrTFrxH4ZlkUCU0SsmFRN0qV6d}

springdoc:
  swagger-ui:
    oauth:
      client-id: murdercase-backend
      client-secret: UOZ81WSrTFrxH4ZlkUCU0SsmFRN0qV6d
    oauth2-redirect-url: http://localhost:8085/swagger-ui/oauth2-redirect.html